openapi: "3.0.0"
info:
  version: 3.0.0
  title: XSS Vulnerability Demo
  description: '<img src="x" onerror="alert(1)" />'
paths:
  /:
    post:
      responses:
        '200':
          description: XSS payload executed
